github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        informational: true
      only_pulls: true
    patch:
      default:
        informational: true

comment:
  layout: "diff, flags, files"