name: CI
on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Lint
        uses: docker://ghcr.io/morphy2k/revive-action:v2
      - name: Test
        uses: robherley/go-test-action@v0
        with:
          testArguments: -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          files: coverage.txt
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
